[package]
name = "test_crate"
version = "0.1.0"
authors = ["Mike Lubinets <public@mersinvald.me>"]
edition = "2018"

[dependencies]
autolog = { path = "../" }
autolog_types = { path = "../autolog_types" }
log = "0.4.6"
env_logger = "0.6.1"
